apiVersion: v1
kind: Secret
metadata:
  name: csgo
  namespace: default
data:
  RCON_PASSWORD: UkNPTl9QQVNTV09SRA==
  SERVER_PASSWORD: U0VSVkVSX1BBU1NXT1JE
  STEAM_ACCOUNT: U1RFQU1fQUNDT1VOVA==
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: csgo
  namespace: default
data:
  SERVER_HOSTNAME: csgo.default.svc.cluster.local
  LAN: "1"
