apiVersion: v1
kind: Secret
metadata:
  name: csgo
  namespace: default
data:
  RCON_PASSWORD: UkNPTl9QQVNTV09SRA==
  SERVER_PASSWORD: U0VSVkVSX1BBU1NXT1JE
  STEAM_ACCOUNT: U1RFQU1fQUNDT1VOVA==
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: csgo
  namespace: default
data:
  SERVER_HOSTNAME: csgo.default.svc.cluster.local
  LAN: "1"
---
apiVersion: v1
kind: Secret
metadata:
  name: factorio
  namespace: default
data:
  rconpw: cmNvbnB3  # Project this into /factorio/config/rconpw
  server-settings.json: InZpc2liaWxpdHkiOgogIHsKICAgICJwdWJsaWMiOiBmYWxzZSwKICAgICJsYW4iOiB0cnVlCiAgfSwK  # Project this into /factorio/config/server-settings.json
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: factorio
  namespace: default
data:
  LOAD_LATEST_SAVE: "false"
  GENERATE_NEW_SAVE: "true"
  SAVE_NAME: "factorio_save"
---
apiVersion: v1
kind: Secret
metadata:
  name: rust
  namespace: default
data:
  RUST_RCON_PASSWORD: UlVTVF9SQ09OX1BBU1NXT1JE
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rust
  namespace: default
data:
  RUST_SERVER_IDENTITY: "rust_game_server"
  RUST_SERVER_NAME: "My Awesome Server"
  RUST_SERVER_DESCRIPTION: "Test Rust server using Kubernetes game-server-operator"
  RUST_SERVER_SEED: "98765"
  RUST_SERVER_STARTUP_ARGUMENTS: "-batchmode -load -logfile /dev/stdout +server.secure 1"
  RUST_SERVER_WORLDSIZE: "500"  # To make start-up faster during testing
---
apiVersion: v1
kind: Secret
metadata:
  name: minecraft
  namespace: default
data:
  RCON_PASSWORD: UkNPTl9QQVNTV09SRA==
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft
  namespace: default
data:
  EULA: "TRUE"
  ENABLE_RCON: "true"
  RCON_PORT: 28016
  SERVER_NAME: "KubernetesOperatorMinecraft"
  # OVERRIDE_SERVER_PROPERTIES: "true"