apiVersion: v1
kind: Secret
metadata:
  name: csgo
  namespace: default
data:
  RCON_PASSWORD: cmNvbnBhc3N3b3Jk
  SERVER_PASSWORD: ""
  STEAM_ACCOUNT: Q0VFMTVDNjk4RDNGODUxOUM2OTRDMEU3NzREOTdDREE=
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: csgo
  namespace: default
data:
  SERVER_HOSTNAME: csgo.default.svc.cluster.local
  LAN: "1"
---
apiVersion: gameserver.martinheinz.dev/v1alpha1
kind: Server
metadata:
  name: csgo
spec:
  serverName: csgo
  gameName: "CSGO"
  envFrom:
    configSource:
      - configMapRef:
          name: csgo
      - secretRef:
          name: csgo
  storage:
    size: 12Gi
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "2"
