apiVersion: gameserver.martinheinz.dev/v1alpha1
kind: Server
metadata:
  name: csgo
spec:
  serverName: csgo
  gameName: "CSGO"
  route: csgo.example.com
  port:  # These are defaults, can be omitted
    - port: 27015
      targetPort: 27015
      nodePort: 30015
  envFrom:
    - configMapRef:
        name: csgo
    - secretRef:
        name: csgo
  storage:
    size: 10Gi
