apiVersion: gameserver.martinheinz.dev/v1alpha1
kind: Server
metadata:
  name: csgo
spec:
  serverName: csgo
  gameName: "CSGO"
  route: csgo.example.com
  port:
    - 27015  # Dummy
  envFrom:
    - configMapRef:
        name: csgo
    - secretRef:
        name: csgo
  storage:
    size: 30Gi
