apiVersion: gameserver.martinheinz.dev/v1alpha1
kind: Server
metadata:
  name: csgo
spec:
  serverName: csgo
  gameName: "CSGO"
  route: csgo.example.com
  port:
    - 27015  # Dummy
  envFrom:
    - configMapRef:
        name: csgo
    - secretRef:
        name: csgo
  storage:
    size: 30Gi
---
# Temporary example of Ingress
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: csgo
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: csgo
              servicePort: 27015
          - path: /
            backend:
              serviceName: csgo
              servicePort: 27020