apiVersion: gameserver.martinheinz.dev/v1alpha1
kind: Server
metadata:
  name: csgo
spec:
  gameName: "CSGO"
  port:  # These are defaults, can be omitted
    - port: 27015
      targetPort: 27015
      nodePort: 30015
  envFrom:
    mountAs: Env
    configSource:
      - configMapRef:
          name: csgo
      - secretRef:
          name: csgo
  storage:
    size: 12Gi
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "2"
