apiVersion: v1
kind: Secret
metadata:
  name: rust
  namespace: default
data:
  RUST_RCON_PASSWORD: UlVTVF9SQ09OX1BBU1NXT1JE
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rust
  namespace: default
data:
  RUST_SERVER_IDENTITY: "rust_game_server"
  RUST_SERVER_NAME: "My Awesome Server"
  RUST_SERVER_DESCRIPTION: "Test Rust server using Kubernetes game-server-operator"
  RUST_SERVER_SEED: "98765"
  RUST_SERVER_STARTUP_ARGUMENTS: "-batchmode -load -logfile /dev/stdout +server.secure 1"
  RUST_SERVER_WORLDSIZE: "500"  # To make start-up faster during testing
---
apiVersion: gameserver.martinheinz.dev/v1alpha1
kind: Server
metadata:
  name: rust
  namespace: default
spec:
  serverName: rust
  gameName: Rust
  envFrom:
    configSource:
      - configMapRef:
          name: rust
      - secretRef:
          name: rust
  resources:
    limits:
      cpu: "2"
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 64Mi
  storage:
    size: 12Gi
